In [1]:
import numpy as np
import random
from numpy import random

In [1]:
def board():
    e=np.array(['a','b','c','d','e','f','g','h','i'])
    w=e.reshape(3,3)
    print(w)
def TicTacToe():
    print('''\nWelcome to play Tic Tac Toe.
    First player will play with X and second player will play with O.
    In the box, there are alphabets from a to i, write a alphabet to replace your entery.
    Player 1 and player 2 will be playing alternatively.''')
    board()
    player1move()
    
    
def checkForWin():
    firstRow=w[0][0]==w[0][1]==w[0][2]
    secondRow=w[1][0]==w[1][1]==w[1][2]
    thirdRow=w[2][0]==w[2][1]==w[2][2]
    firstColumn=w[0][0]==w[1][0]==w[2][0]
    secondColumn=w[0][1]==w[1][1]==w[2][1]
    thirdColumn=w[0][2]==w[1][2]==w[2][2]
    lrDiagonal=w[0][0]==w[1][1]==w[2][2]
    rlDiagonal=w[0][2]==w[1][1]==w[2][0]
#     while 54:
    if firstRow or secondRow or thirdRow or firstColumn or secondColumn or thirdColumn or lrDiagonal or rlDiagonal:
        if firstRow:
            print('\nCongratulations, {} have won the match.'.format(w[0][1]))
            replay=input('\nWould you like to play again? Enter Y for Yes or anything for No: ')
            if replay.lower()=='y':
                TicTacToe()
            else:
                print('\nThank you for playing.')
#                     break
        elif secondRow:
            print('\nCongratulations, {} have won the match.'.format(w[1][1]))
            replay=input('\nWould you like to play again? Enter Y for Yes or anything for No: ')
            if replay.lower()=='y':
                TicTacToe()
            else:
                print('\nThank you for playing.')
#                     break
        elif thirdRow:
            print('\nCongratulations, {} have won the match.'.format(w[2][1]))
            replay=input('\nWould you like to play again? Enter Y for Yes or anything for No: ')
            if replay.lower()=='y':
                TicTacToe()
            else:
                print('\nThank you for playing.')
#                     break
        elif firstColumn:
            print('\nCongratulations, {} have won the match.'.format(w[1][0]))
            replay=input('\nWould you like to play again? Enter Y for Yes or anything for No: ')
            if replay.lower()=='y':
                TicTacToe()
            else:
                print('\nThank you for playing.')
#                     break
        elif secondColumn:
            print('\nCongratulations, {} have won the match.'.format(w[1][1]))
            replay=input('\nWould you like to play again? Enter Y for Yes or anything for No: ')
            if replay.lower()=='y':
                TicTacToe()
            else:
                print('\nThank you for playing.')
#                     break
        elif thirdColumn:
            print('\nCongratulations, {} have won the match.'.format(w[1][2]))
            replay=input('\nWould you like to play again? Enter Y for Yes or anything for No: ')
            if replay.lower()=='y':
                TicTacToe()
            else:
                print('\nThank you for playing.')
#                     break
        elif lrDiagonal:
            print('Congratulations, {} have won the match.'.format(w[1][1]))
            replay=input('\nWould you like to play again? Enter Y for Yes or anything for No: ')
            if replay.lower()=='y':
                TicTacToe()
            else:
                print('\nThank you for playing.')
#                     break
        elif rlDiagonal:
            print('\nCongratulations, {} have won the match.'.format(w[1][1]))
            replay=input('Would you like to play again? Enter Y for Yes or anything for No: ')
            if replay.lower()=='y':
                TicTacToe()
            else:
                print('\nThank you for playing.')
#                     break
    elif w[0][0]!='a' and w[0][1]!='b' and w[0][2]!='c' and w[1][0]!='d' and w[1][1]!='e' and w[1][2]!='f' and w[2][0]!='g' and w[2][1]!='h' and w[2][2]!='i':
        print('\nMatch is drawn.')
        replay=input('\nWould you like to play again? Enter Y for Yes or anything for No: ')
        if replay.lower()=='y':
            TicTacToe()
        else:
            print('\nThank you for playing.')     
#                 break

            
def player1move():
    while 53:
        g=input('\nEnter a alphabet from a to i: ')
        if g.lower()=='a':
            w[0][0]='X'
            print(w)
            checkForWin()
            player2move()
        elif g.lower()=='b':
            w[0][1]='X'
            print(w)
            checkForWin()
            player2move()
        elif g.lower()=='c':
            w[0][2]='X'
            print(w)
            checkForWin()
            player2move()
        elif g.lower()=='d':
            w[1][0]='X'
            print(w)
            checkForWin()
            player2move()
        elif g.lower()=='e':
            w[1][1]='X'
            print(w)
            checkForWin()
            player2move()
        elif g.lower()=='f':
            w[1][2]='X'
            print(w)
            checkForWin()
            player2move()
        elif g.lower()=='g':
            w[2][0]='X'
            print(w)
            checkForWin()
            player2move()
        elif g.lower()=='h':
            w[2][1]='X'
            print(w)
            checkForWin()
            player2move()
        elif g.lower()=='i':
            w[2][2]='X'
            print(w)
            checkForWin()
            player2move()
        else:
            print('Please enter desire input only.')

            
def player2move():
    while 53:
        g=input('\nEnter a alphabet from a to i: ')
        if g.lower()=='a':
            w[0][0]='O'
            print(w)
            checkForWin()
            player1move()
        elif g.lower()=='b':
            w[0][1]='O'
            print(w)
            checkForWin()
            player1move()
        elif g.lower()=='c':
            w[0][2]='O'
            print(w)
            checkForWin()
            player1move()
        elif g.lower()=='d':
            w[1][0]='O'
            print(w)
            checkForWin()
            player1move()
        elif g.lower()=='e':
            w[1][1]='O'
            print(w)
            checkForWin()
            player1move()
        elif g.lower()=='f':
            w[1][2]='O'
            print(w)
            checkForWin()
            player1move()
        elif g.lower()=='g':
            w[2][0]='O'
            print(w)
            checkForWin()
            player1move()
        elif g.lower()=='h':
            w[2][1]='O'
            print(w)
            checkForWin()
            player1move()
        elif g.lower()=='i':
            w[2][2]='O'
            print(w)
            checkForWin()
            player1move()
        else:
            print('Please enter desire input only.')
            
TicTacToe()            


Welcome to play Tic Tac Toe.
    First player will play with X and second player will play with O.
    In the box, there are alphabets from a to i, write a alphabet to replace your entery.
    Player 1 and player 2 will be playing alternatively.


NameError: name 'np' is not defined

In [ ]:
np.random([5,2])

In [ ]:
random.rand()

In [ ]:
random.randint(1,5)

In [ ]:
d=np.array([1,2,3])

In [ ]:
rossy=list(d)
rossy

In [ ]:
import pygame

In [14]:
import pygame as pg,sys
from pygame.locals import *
import time
#initialize global variables
XO = 'x'
winner = None
draw = False
width = 400
height = 400
white = (255, 255, 255)
line_color = (10,10,10)
#TicTacToe 3x3 board
TTT = [[None]*3,[None]*3,[None]*3]


In [ ]:
i,j,cb=(2,6,8)

In [ ]:
i

In [ ]:
cb

In [4]:
import numpy as np

def create_board():
    return (np.array([[0, 0, 0],
                      [0, 0, 0],
                      [0, 0, 0]]))


def coordinates(board, player):
    i, j, cn = (-1, -1, 0)
    while (i > 3 or i < 0 or j < 0 or j > 3) or (board[i][j] != 0):
        if cn > 0:
            print("Wrong Input! Try Again")
        print("Player {}'s turn".format(player))
        i = int(input("x-coordinates: "))
        j = int(input("y-coordinates: "))
        i = i - 1
        j = j - 1
        cn = cn + 1
    board[i][j] = player
    return board


def row_win(board, player):
    for x in range(len(board)):
        win = True

        for y in range(len(board)):
            if board[x, y] != player:
                win = False
                continue
    return win


def col_win(board, player):
    for x in range(len(board)):
        win = True

        for y in range(len(board)):
            if board[y][x] != player:
                win = False
                continue

    return win


def diag_win(board, player):
    win = True
    y = 0
    for x in range(len(board)):
        if board[x][x] != player:
            win = False
    if win:
        return win
    win = True
    if win:
        for x in range(len(board)):
            y = len(board) - 1 - x
            if board[x][y] != player:
                win = False
    return win


def evaluate(board):
    winner = 0

    for player in [1, 2]:
        if (row_win(board, player) or
                col_win(board, player) or
                diag_win(board, player)):
            winner = player

    if np.all(board != 0) and winner == 0:
        winner = -1
    return winner


def play_game():
    board, winner, counter = create_board(), 0, 1
    print(board)
    while winner == 0:
        for player in [1, 2]:
            board = coordinates(board, player)
            print("Board after " + str(counter) + " move")
            print(board)
            counter += 1
            winner = evaluate(board)
            if winner != 0:
                break
    return winner

print("Winner is: " + str(play_game()))

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Player 1's turn
x-coordinates: 2
y-coordinates: 2
Board after 1 move
[[0 0 0]
 [0 1 0]
 [0 0 0]]
Player 2's turn
x-coordinates: 1
y-coordinates: 1
Board after 2 move
[[2 0 0]
 [0 1 0]
 [0 0 0]]
Player 1's turn
x-coordinates: 1
y-coordinates: 2
Board after 3 move
[[2 1 0]
 [0 1 0]
 [0 0 0]]
Player 2's turn
x-coordinates: 2
y-coordinates: 1
Board after 4 move
[[2 1 0]
 [2 1 0]
 [0 0 0]]
Player 1's turn
x-coordinates: 2
y-coordinates: 1
Wrong Input! Try Again
Player 1's turn
x-coordinates: 3
y-coordinates: 1
Board after 5 move
[[2 1 0]
 [2 1 0]
 [1 0 0]]
Player 2's turn
x-coordinates: 3
y-coordinates: 3
Board after 6 move
[[2 1 0]
 [2 1 0]
 [1 0 2]]
Player 1's turn
x-coordinates: 3
y-coordinates: 2
Board after 7 move
[[2 1 0]
 [2 1 0]
 [1 1 2]]
Player 2's turn
x-coordinates: 1
y-coordinates: 3
Board after 8 move
[[2 1 2]
 [2 1 0]
 [1 1 2]]
Player 1's turn
x-coordinates: 2
y-coordinates: 3
Board after 9 move
[[2 1 2]
 [2 1 1]
 [1 1 2]]
Winner is: -1


In [ ]:
f=np.array([' ',' ',' ',
           ' ',' ',' ',
           ' ',' ',' '])

In [ ]:
f

In [ ]:
f.shape

In [ ]:
f1=f.reshape(3,3)
f1

In [ ]:
n=np.array([1,2,3,4,5,6,7,8,9])

In [ ]:
n1=n.reshape(3,3)
n1

In [ ]:
n1[1][2]=4

In [ ]:
f

In [ ]:
n1

In [ ]:
def x_turn():
    while 354:
        x=int(input('Enter no. of row between 0 and 2: '))
        y=int(input('Enter no. of column between 0 and 2: '))
        f1[x][y]='X'
        print(f1)
        y_turn()

In [ ]:
def y_turn():
    while 354:
        x=int(input('Enter no. of row between 0 and 2: '))
        y=int(input('Enter no. of column between 0 and 2: '))
        f1[x][y]='O'
        print(f1)
        x_turn()

In [ ]:
f1

In [ ]:
x_turn()

In [ ]:
for i in range(0,3):
    for j in range(0,3):
        if f1[i][j]!=' ':
            print(i,j,'yes')

In [ ]:
len(f1)-1

In [ ]:
f1

In [ ]:
e=np.array([' ','|',' ','|',' ','_','_','_','_','_',' ','|',' ','|',' ','_','_','_','_','_',' ','|',' ','|',' '])

In [ ]:
e

In [ ]:
e.shape

In [ ]:
e.reshape(5,5)

In [ ]:
f1

In [ ]:
f

In [ ]:
for i in range(3):
    for j in range(3):
        if f1[i][j]=='X':
            print(i,j)

In [ ]:
len(f1)

In [ ]:
r=np.array([' ',' ',' ',
           ' ',' ',' ',
           ' ',' ',' '])

In [ ]:
ro=r.reshape(3,3)

In [ ]:
ro

In [ ]:
def checkForWin():
    firstRow=w[0][0]==w[0][1]==w[0][2]
    secondRow=w[1][0]==w[1][1]==w[1][2]
    thirdRow=w[2][0]==w[2][1]==w[2][2]
    firstColumn=w[0][0]==w[1][0]==w[2][0]
    secondColumn=w[0][1]==w[1][1]==w[2][1]
    thirdColumn=w[0][2]==w[1][2]==w[2][2]
    lrDiagonal=w[0][0]==w[1][1]==w[2][2]
    rlDiagonal=w[0][2]==w[1][1]==w[2][0]
    if firstRow or secondRow or thirdRow or firstColumn or secondColumn or thirdColumn or lrDiagonal or rlDiagonal:
        if firstRow:
            print('\nCongratulations, {} have won the match.'.format(w[0][1]))
            replay=input('\nWould you like to play again? Enter Y for Yes or anything for No: ')
            if replay.lower()=='y':
                TicTacToe()
            else:
                print('\nThank you for playing.')
        elif secondRow:
            print('\nCongratulations, {} have won the match.'.format(w[1][1]))
            replay=input('\nWould you like to play again? Enter Y for Yes or anything for No: ')
            if replay.lower()=='y':
                TicTacToe()
            else:
                print('\nThank you for playing.')
        elif thirdRow:
            print('\nCongratulations, {} have won the match.'.format(w[2][1]))
            replay=input('\nWould you like to play again? Enter Y for Yes or anything for No: ')
            if replay.lower()=='y':
                TicTacToe()
            else:
                print('\nThank you for playing.')
        elif firstColumn:
            print('\nCongratulations, {} have won the match.'.format(w[1][0]))
            replay=input('\nWould you like to play again? Enter Y for Yes or anything for No: ')
            if replay.lower()=='y':
                TicTacToe()
            else:
                print('\nThank you for playing.')
        elif secondColumn:
            print('\nCongratulations, {} have won the match.'.format(w[1][1]))
            replay=input('\nWould you like to play again? Enter Y for Yes or anything for No: ')
            if replay.lower()=='y':
                TicTacToe()
            else:
                print('\nThank you for playing.')
        elif thirdColumn:
            print('\nCongratulations, {} have won the match.'.format(w[1][2]))
            replay=input('\nWould you like to play again? Enter Y for Yes or anything for No: ')
            if replay.lower()=='y':
                TicTacToe()
            else:
                print('\nThank you for playing.')
        elif lrDiagonal:
            print('Congratulations, {} have won the match.'.format(w[1][1]))
            replay=input('\mWould you like to play again? Enter Y for Yes or anything for No: ')
            if replay.lower()=='y':
                TicTacToe()
            else:
                print('\nThank you for playing.')
        elif rlDiagonal:
            print('\nCongratulations, {} have won the match.'.format(w[1][1]))
            replay=input('Would you like to play again? Enter Y for Yes or anything for No: ')
            if replay.lower()=='y':
                TicTacToe()
            else:
                print('\nThank you for playing.')
    elif w[0][0]!='a' and w[0][1]!='b' and w[0][2]!='c' and w[1][0]!='d' and w[1][1]!='e' and w[1][2]!='f' and w[2][0]!='g' and w[2][1]!='h' and w[2][2]!='i':
        print('\nMatch is drawn.')
        replay=input('\nWould you like to play again? Enter Y for Yes or anything for No: ')
        if replay.lower()=='y':
            TicTacToe()
        else:
            print('\nThank you for playing.')               

In [ ]:
print(w)
checkForWin()

In [ ]:
x=y=z=0
x

In [ ]:
if x==y==0:
    print('rg')

In [ ]:
checkForWin()

In [ ]:
ro[0][2]

In [ ]:
ro[2][2]

In [ ]:
def checkForWinning():
    if ro[0][0]==ro[0][1] and ro[0][1]==r[0][2]:
        print('Congratulations, {} have won the match.'.format(x))

In [ ]:
checkForWinning()

In [ ]:
 or ro[1][0]==ro[1][1]==r[1][2] or ro[2][0]==ro[2][1]==r[2][2] or  ro[0][0]==ro[1][0]==r[2][0] or ro[0][1]==ro[1][1]==r[2][1] or ro[0][2]==ro[1][2]==r[2][2] or ro[0][0]==r[1][1]==ro[2][2] or ro[0][2]==r[1][1]==r[2][0]

In [ ]:
ro[0][0]

In [ ]:
ro[0][1]

In [ ]:
r[0][2]

In [ ]:
ro.shape

In [ ]:
ro[0][2]

In [ ]:
x=5
y=6
z=4
a=x==4
b=y==6
if a or b:
    print('f')
    print(a,b)

In [ ]:
ro

In [ ]:
e=np.array(['a','b','c','d','e','f','g','h','i'])
w=e.reshape(3,3)
w

In [ ]:
e=np.array(['a','b','c','d','e','f','g','h','i'])
w=e.reshape(3,3)
print(w)
TicTacToe()

In [ ]:
w

In [ ]:
result =np.where(w=='h')

In [ ]:
print(result)

In [ ]:
e=np.array(['a','b','c','d','e','f','g','h','i'])
w=e.reshape(3,3)
print(w)
TicTacToe()

In [ ]:
e=np.array(['a','b','c','d','e','f','g','h','i'])
w=e.reshape(3,3)
print(w)
TicTacToe()

In [ ]:
TicTacToe()

In [ ]:
rossy_Kassi_Padmini=45

In [ ]:
def kamini():
    rossy=24
    return rossy, rossy_Kassi_Padmini

In [ ]:
kamini()

In [ ]:
print(rossy)

In [ ]:
h=24
r=45.24
def commutepay(h,r):
    return 'Rossy work worth is: ',h*r

In [ ]:
commutepay(354,10000)

In [3]:
def ehi():
    f=23
    rt()
def rt():
    print(f)
ehi()

NameError: name 'f' is not defined

In [15]:
#Harshil Sir's

import numpy as np 
import random 
from time import sleep 

# Creates an empty board 
def initializeBoard(): 
    return(np.array([[0, 0, 0], 
                     [0, 0, 0], 
                     [0, 0, 0]]))

def checkPossibility(board, r, c):
    if(board[r][c] == 0):
        return True
    else:
        return False

def playersName():
    firstPlayer = (str(input("What is the first player name? ")))
    secondPlayer = (str(input("What is the second player name? ")))
    playersDict = {1: firstPlayer, 2: secondPlayer}
    print(playersDict)
    return playersDict

def markPosition(board, player):
    possible = False
    while(possible != True):
        r = int(input("Which Row you want to mark? "))
        c = int(input("Which Column you want to mark? "))
        possible = checkPossibility(board, r, c)
        if possible:
            board[r][c] = player
        else:
            print("\nThis position is already marked, try again")
    return board
#player = 2
#board = markPosition(board, player)

# Checks whether the player has three of their marks in a horizontal row 
def rowWin(board, player): 
    for x in range(len(board)): 
        win = True
        for y in range(len(board)): 
            if board[x, y] != player: 
                win = False
                continue
        if win == True: 
            return(win) 
    return(win) 

# Checks whether the player has three of their marks in a vertical row 
def colWin(board, player): 
    for x in range(len(board)): 
        win = True
        for y in range(len(board)): 
            if board[y][x] != player: 
                win = False
                continue
        if win == True: 
            return(win) 
    return(win)

# Checks whether the player has three of their marks in a diagonal row 
def diaWin(board, player): 
    win = True
    for x in range(len(board)): 
        if board[x, x] != player: 
            win = False
    return(win)

# Evaluates whether there is a winner or a tie 
def evaluate(board): 
	winner = 0
	
	for player in [1, 2]: 
		if (rowWin(board, player) or colWin(board,player) or diaWin(board,player)): 	
			winner = player 	
	if np.all(board != 0) and winner == 0: 
		winner = -1
	return winner 

def playGame(playersDict): 
    board = initializeBoard()
    print("Start Game:\n")
    print(board) 
    sleep(1)
    winner, counter = 0, 1
    while winner == 0: 
        for player in [1, 2]: 
            print("\nChance of " + playersDict[player])
            board = markPosition(board, player) 
            print("Board after " + playersDict[player] + "'s move") 
            print(board) 
            sleep(0.5) 
            counter += 1
            winner = evaluate(board) 
            if winner != 0: 
                break
    return(winner)

playersDict = playersName()
Winner = playGame(playersDict)
print("\nWinner is: " + str(playersDict[Winner])) 


What is the first player name? Rossy
What is the second player name? Gunnu
{1: 'Rossy', 2: 'Gunnu'}
Start Game:

[[0 0 0]
 [0 0 0]
 [0 0 0]]

Chance of Rossy
Which Row you want to mark? 1
Which Column you want to mark? 2
Board after Rossy's move
[[0 0 0]
 [0 0 1]
 [0 0 0]]

Chance of Gunnu
Which Row you want to mark? 1
Which Column you want to mark? 1
Board after Gunnu's move
[[0 0 0]
 [0 2 1]
 [0 0 0]]

Chance of Rossy
Which Row you want to mark? 0
Which Column you want to mark? 2
Board after Rossy's move
[[0 0 1]
 [0 2 1]
 [0 0 0]]

Chance of Gunnu
Which Row you want to mark? 1
Which Column you want to mark? 0
Board after Gunnu's move
[[0 0 1]
 [2 2 1]
 [0 0 0]]

Chance of Rossy
Which Row you want to mark? 0
Which Column you want to mark? 2

This position is already marked, try again
Which Row you want to mark? 2
Which Column you want to mark? 2
Board after Rossy's move
[[0 0 1]
 [2 2 1]
 [0 0 1]]

Winner is: Rossy


In [16]:
e=np.array(['a','b','c','d','e','f','g','h','i'])
w=e.reshape(3,3)
print(w)


[['a' 'b' 'c']
 ['d' 'e' 'f']
 ['g' 'h' 'i']]


In [17]:
w[2,2]

'i'

In [19]:
from time import sleep
print('erg')
sleep(5)
print('ergrg')

erg
ergrg


In [20]:
time.gmtime(0)

time.struct_time(tm_year=1970, tm_mon=1, tm_mday=1, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=3, tm_yday=1, tm_isdst=0)

In [24]:
for x in range(5):
    print(time.ctime())
    sleep(2)

Fri Nov  5 18:37:26 2021
Fri Nov  5 18:37:28 2021
Fri Nov  5 18:37:30 2021
Fri Nov  5 18:37:32 2021
Fri Nov  5 18:37:34 2021


In [23]:
time.ctime()

'Fri Nov  5 18:37:03 2021'

In [29]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)
c=list(x)
print(c)

[array([3, 5, 6], dtype=int64)]


In [37]:
import numpy as np

arr = np.array([6, 7, 8, 9])
# arR=arr.reshape(2,2)
# print(arR)
x = np.searchsorted(arr, 8)

print(x)

2


In [40]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 8, side='right')

print(x)

3


In [42]:

import numpy as np

arr = np.array([1, 3, 7, 7])

x = np.searchsorted(arr, [2, 4, 61])

print(x)

[1 2 4]


In [43]:
w

array([['a', 'b', 'c'],
       ['d', 'e', 'f'],
       ['g', 'h', 'i']], dtype='<U1')

In [44]:
np.where(w=='g')

(array([2], dtype=int64), array([0], dtype=int64))

In [45]:
c=2
def eree():
    c+=4
    return c
eree()

UnboundLocalError: local variable 'c' referenced before assignment